// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://csrvybzmipontustwcbf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzcnZ5YnptaXBvbnR1c3R3Y2JmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMjc3NTksImV4cCI6MjA2MzYwMzc1OX0.l9M2twN59MqfWyv5G5w8pyaYjMRNWfr3Zbl-fOZGJZM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);